
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AnnouncementBar from "./components/header/AnnouncementBar/AnnouncementBar";
import Navbar from "./components/header/Navbar/Navbar";
import StoreProvider from "./StoreProvider";
import { Toaster } from "@/components/ui/sonner";
import Footer from "./components/footer/Footer";
import NotificationsListener from "./components/NotificationsListener";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
            <head>
        <link
          href="https://api.fontshare.com/v2/css?f[]=satoshi@100,200,300,400,500,600,700,800,900&display=swap"
          rel="stylesheet"
        />
        <link href="https://fonts.googleapis.com/css2?family=Anton&display=swap" rel="stylesheet"/>
 
        <link href="https://fonts.googleapis.com/css2?family=League+Spartan:wght@400;500;600;700;800;900&display=swap" rel="stylesheet"/>

        <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet"/>

      </head>

      <body
        className={`antialiased`}
      >
        <StoreProvider>
          <AnnouncementBar/>
        <Navbar/>
        
        {children}
        <Footer/>
          <Toaster position="top-right" richColors/>
          <NotificationsListener/>
        </StoreProvider>
      </body>
    </html>
  );
}
